// Simulated DOM behavior only; not a browser/GPU rendering test.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('apercu_spring_applewoods_v2.html','utf8');let raf;const els={};
class E{constructor(){this.children=[];this.style={};this.value=''}add(o){this.children.push(o);if(!this.value)this.value=o.value}append(...nodes){this.children.push(...nodes)}replaceChildren(){this.children=[]}setAttribute(k,v){this[k]=v}}
const doc={getElementById(id){if(!els[id]){els[id]=new E();if(id==='mode')els[id].value='jour'}return els[id]},createElement(){return new E()},createTextNode(t){return t}};
const ctx={document:doc,Option:class{constructor(text,value){this.text=text;this.value=value}},performance:{now:()=>100},requestAnimationFrame(f){raf=f},console};vm.createContext(ctx);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],ctx);
let cases=0;
for(let project=0;project<3;project++)for(const mode of ['jour','nuit']){els.project.value=String(project);els.mode.value=mode;els.project.onchange();assert.equal(els.stage.children.length,project===0?5:32);raf(200);for(const image of els.stage.children)assert(image.src.startsWith('data:image/png;base64,'));const row=els.layers.children.at(-1),check=row.children[0].children[0],range=row.children[1],image=els.stage.children.at(-1);check.checked=false;check.onchange();assert.equal(image.style.visibility,'hidden');range.value=35;range.oninput();assert.equal(image.style.opacity,.35);els.reset.onclick();assert(els.layers.children.at(-1).children[0].children[0].checked);if(project===0){for(let f=0;f<78;f++){els.phase.value=f;els.phase.oninput();assert(els.frame.textContent.startsWith(String(f+1)+' /'));}els.pause.onclick();raf(650);assert.equal(els.pause.textContent,'Pause')}cases++}
const result={status:'PASS',project_mode_cases:cases,all78_spring_phases:true,layer_visibility_and_opacity:true,reset_and_playback:true,real_browser_GPU_tested:false};fs.writeFileSync('renders/corrections_spring_tours_v2/verification_viewer.json',JSON.stringify(result,null,2));console.log(result);
