"""Prepare a per-request image-generation prompt. Does NOT call or retrain a model."""
import argparse,json
from pathlib import Path
C=json.loads(Path(__file__).with_name('contract.json').read_text())
def make(brief,kind,emotion='Normal',direction='Down'):
 species=brief.get('species','')
 if not species or species.startswith('<'):raise ValueError('Specify the Pokemon species first')
 refs=brief.get('references',[])
 if not refs:raise ValueError('Add verified canonical/native references before generation')
 identity=f"Pokemon: {species}. Form/design: {brief.get('form_description','canonical form')}. Individual traits/accessories: {brief.get('custom_traits','none')}. Asymmetry that must remain consistent: {brief.get('asymmetry','must be checked against references')}."
 common=identity+' Use the supplied canonical design and Chunsoft PMD reference images as the anatomical and style guide. This output is a drawing/reference draft for deliberate pixel cleanup, not an engine-ready asset. No text, labels, watermark, interface or decorative frame. Do not invent features or change body proportions between views. '
 if kind=='portrait':
  if brief.get('spritecollab_slot') in C['portrait'].get('blocked_subject_slots',{}):
   raise ValueError(C['portrait']['blocked_subject_slots'][brief['spritecollab_slot']])
  normal=brief.get('normal_portrait_reference')
  if emotion!='Normal' and (not normal or normal not in refs):
   raise ValueError('Non-Normal expressions require the native/approved Normal portrait explicitly included in references')
  slot=brief.get('spritecollab_slot') or ''
  if slot.split('/')[0]=='0026' or 'raichu' in species.lower():
   common+=' Raichu expressions must be natural to its rodent muzzle: NO human lips, lip biting/sucking, visible teeth, human grimaces or invented facial folds. Pain is primarily expressed through eyelids and a small closed animal mouth. '
  if slot.split('/')[0]=='0564' or any(n in species.lower() for n in ['tirtouga','carapagos']):
   common+=' Keep the approved Normal turtle face and its beak/nostril anatomy. Natural beak opening IS allowed when supported by a canonical reference, with no visible teeth. Do not impose a closed beak for every emotion. Keep unaffected traits fixed, never invent human lips or a redesigned muzzle. Preserve all previously approved portraits including the open-mouth versions. '
  common+=' Expressions must follow the actual species anatomy, never a generic human face pasted onto an animal muzzle. Do not invent lips, human teeth or facial traits absent from the canonical reference. '
  if slot.split('/')[0]=='0186' or any(n in species.lower() for n in ['politoed','tarpaud']):
   common+=' Politoed has one frog mouth at the green-upper-face/yellow-lower-jaw seam. NEVER draw a second smile or frown inside the yellow jaw. Natural mouth opening may follow the existing canonical open-mouth portraits; no human lips or teeth. '
  common+=' The supplied Normal portrait is the FIXED anatomical master. Preserve the exact face silhouette, proportions, muzzle, nose, cheek placement, eye implantation and characteristic design, ears, markings, perspective and framing. Only eyelids, brows and mouth may move naturally for the expression; never replace or redesign facial traits. Begin with one restrained expression trial, not a sheet. Technical compliance cannot excuse anatomical drift. '
  if emotion not in C['portrait']['emotions']:raise ValueError('Use a configured emotion slot; describe custom nuance in the brief')
  return common+f"Create ONE emotion portrait, {emotion}, not a contact sheet. Tight expressive head composition intended for a 40 by 40 pixel PMD Explorers portrait. Make the large drawing roughly 400 by 400 compositionally; final 40 by 40 raster and palette will be constructed and checked separately. When deriving an expression, keep the Normal portrait view and framing exactly; do not invent a new face angle or head tilt. Derive natural eyelid, brow and mouth movements from its existing facial anatomy. Keep important ears, muzzle and species identifiers legible at native scale. Emulate the softly clustered, illustrated Chunsoft portrait look: colored dark outlines, controlled cel shading, a few opaque hand-placed blend colors, no uniform heavy pure-black outline, no smooth 3D rendering, photorealism, bloom or noisy dithering. GENERATION STAGE: isolate the subject on a perfectly flat solid #FF00FF MAGENTA background, including empty gaps. No canonical background, checkerboard, texture or scene painted by the generator. Preserve genuine pink cheeks/markings as their native colors, distinct from the removable magenta. POSTPROCESSING ONLY: chroma-key the magenta into alpha, perform native40x40 anatomical cleanup, then compose onto the EXACT designated emotion cell cropped from template.png; Extra_Backgrounds.png requires an explicit chosen cell. Preserve canonical background pixels rather than regenerating them. Budget the final subject plus background to fifteen colors. Only the FINAL COMPOSITE must be completely opaque, without leftover magenta or transparent holes. "+brief.get('emotion_notes',{}).get(emotion,'')
 if direction not in C['sprite']['directions']:raise ValueError('Unknown PMD direction')
 return common+f"Create ONE full-body Idle key-pose guide facing {direction}. Match the exact oblique PMD dungeon camera, native reference body scale and grounded center. Keep every limb, marking and attachment anatomically consistent. Crisp small pixel clusters, readable silhouette, restrained shading and a planned fifteen-visible-color palette shared with ALL future animations. Use flat solid magenta only as a removable intermediate matte if transparency is unavailable, with no magenta on the character. No ground, scene, painted shadow, blur, bloom, alpha gradients or illustration background. Do NOT draw technical offset markers: they will be authored as separate PNG sheets, as will the engine shadow. Do not produce the final 8-direction animation grid in this drawing; approved native-size poses will be registered, retouched and animated separately. "
if __name__=='__main__':
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('brief',type=Path);p.add_argument('kind',choices=['portrait','sprite']);p.add_argument('--emotion',default='Normal');p.add_argument('--direction',default='Down');a=p.parse_args();print(make(json.loads(a.brief.read_text()),a.kind,a.emotion,a.direction))
