from pathlib import Path
import base64
ROOT=Path(__file__).resolve().parents[2]
SCENE=ROOT/'exports/guild_scene_animations_v1'
PORTRAIT=ROOT/'exports/pokemon_custom/politoed_portraits_v3'
def image(p):
 return 'data:image/'+('gif' if p.suffix=='.gif' else 'png')+';base64,'+base64.b64encode(p.read_bytes()).decode()
def main():
 html='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Guilde · Tarpaud et premières scènes</title><style>body{margin:32px auto;padding:0 24px;max-width:1150px;background:#141d2b;color:#edf4fa;font:16px system-ui}p,li{line-height:1.65;color:#bed0df}h1{font-size:34px}h2{margin-top:38px}section,.card{background:#202e42;padding:20px;border-radius:14px;margin:20px 0}img{image-rendering:pixelated;max-width:100%}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.card{margin:0;text-align:center}.card h3{font-size:18px}.notice{border-left:3px solid #f4c477;padding:12px 18px}small{color:#bed0df}.portrait{width:240px}.frames{width:100%}a{color:#a8d7fd}</style><h1>Guilde · Tarpaud et premières scènes</h1><p>V1 de Tarpaud conservée. Réutilisation des vraies animations Cutscene avant création des manques.</p><p class="notice"><strong>Travail en cours :</strong> les deux packs passent le précontrôle technique local. Aucun test dans PMDO. Nod reste un candidat de face ; les sept autres directions et les autres manques ne sont pas terminés.</p><h2>Tarpaud : uniquement les deux changements demandés</h2><p>13 portraits V1 inchangés octet par octet. Dizzy remplacé par une spirale continue ; ajout Special0 applaudissant, œil fermé et bouche naturellement ouverte. V2 écartée. Sigh/Stunned restent absents.</p><section><img class="frames" alt="Normal conservé, Dizzy spirale, applaudissements, Happy et Shouting conservés" src="'''+image(PORTRAIT/'review/changes_x4.png')+'"></section><div class="grid">'
 for name,label in [('Dizzy','Dizzy · spirale continue'),('Special0','Special0 · applaudissements')]:
  html+='<div class="card"><h3>'+label+'</h3><img class="portrait" alt="'+label+'" src="'+image(PORTRAIT/f'portraits_individual/{name}.png')+'"><p>Proposition40×40 sur fond canonique exact.</p></div>'
 html+='</div><h2>Gardevoir · nouveau Nod de face</h2><section><img alt="Animation Nod de face" src="'+image(SCENE/'review/Gardevoir_Nod_front_candidate.gif')+'"><p>3 dessins, 5 étapes. Têtes générées puis nettoyées ; robe, corps, ombre et repères natifs stabilisés. Les autres lignes générées changeaient de direction : elles ont été rejetées, pas transformées en fausses vues valides.</p><img class="frames" alt="Cinq étapes du hochement de tête" src="'+image(SCENE/'review/Nod_frames.png')+'"></section><h2>Gardevoir · 7 actions canoniques réutilisées</h2><p>Toutes les14actions de base sont conservées. Special1 utilise les vrais dessins Appeal Cutscene, pas l’Appeal différent de la base. Les GIFs ci-dessous sont des ressources natives récupérées, pas7nouvelles générations. StandingUp est une posture fixe ; Special0/Special2 comprennent des images transparentes, et Special3 clignote volontairement dans la source canonique. Ces états/effets ne sont pas tous des gestes de dialogue.</p><div class="grid">'
 for name in ['StandingUp','Special0','Special1','Special2','Special3','Pose','Jump']:
  html+='<div class="card"><h3>'+name+' · natif</h3><img alt="Gardevoir '+name+' canonique" src="'+image(SCENE/f'review/Gardevoir_{name}_native.gif')+'"></div>'
 html+='</div><h2>Dimoret · 2 gestes Cutscene canoniques</h2><p>Les13actions de base restent intactes. Ces Specials ne sont pas renommés Nod/Pose pour gonfler artificiellement le nombre de manques résolus.</p><div class="grid">'
 for name in ['Special0','Special1']:
  html+='<div class="card"><h3>'+name+' · natif</h3><img alt="Dimoret '+name+' canonique" src="'+image(SCENE/f'review/Weavile_{name}_native.gif')+'"></div>'
 html+='</div><h2>Livrables et suite</h2><ul><li>Portraits : exports/pokemon_custom/politoed_portraits_v3/.</li><li>Packs XML + triples : exports/guild_scene_animations_v1/gardevoir_candidate/ et weavile_canonical/.</li><li>Crédits originaux et rapports techniques conservés à côté des packs.</li><li>Réutilisation : seule Pose comble un manque générique du profil32. Les9actions Cutscene ne sont pas9créations inédites.</li><li>Continuer les animations manquantes de guilde ; ensuite Team Dazzling (Lockpin/Mysdibule/Sucreine), vraie transition PMDO, puis maps.</li></ul><p class="notice">Images/GIFs contrôlés et formats vérifiés ≠ approbation artistique, acceptation SpriteCollab ou import/runtime Ground/Dungeon.</p></html>'
 (ROOT/'apercu_guilde_scenes_v1.html').write_text(html)
if __name__=='__main__':main()
