/* DOM/state tests, not a graphical browser or PMDO runtime test. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),cp=require('child_process');
const R=path.resolve(__dirname,'../..'),O=path.join(R,'renders/spinda_torches_v1'),temp=path.join(R,'.cache/spinda_torches/package');
fs.rmSync(temp,{recursive:true,force:true});
cp.execFileSync(path.join(R,'.venv/bin/python'),['-c',`import zipfile;zipfile.ZipFile(${JSON.stringify(path.join(O,'Spinda_torches_8angles_animees.zip'))}).extractall(${JSON.stringify(temp)})`]);
async function check(file){
 const html=fs.readFileSync(file,'utf8');if(html.includes('http-equiv="refresh"')){assert(html.includes('url=renders/spinda_torches_v1/index.html'));assert(fs.existsSync(path.join(O,'index.html')));console.log('PASS root redirect');return}const script=html.match(/<script>([\s\S]*?)<\/script>/)[1],all=[],ids={},downloads=[],timers=[];
 class Context{constructor(){this.ops=[]}clearRect(){this.ops=[]}drawImage(im,...args){this.ops.push({op:'image',src:im.src,args,composite:this.globalCompositeOperation||'source-over',alpha:this.globalAlpha??1})}fillRect(){this.ops.push({op:'fill',color:this.fillStyle})}strokeRect(){this.ops.push({op:'guide'})}fillText(){this.ops.push({op:'guide'})}beginPath(){}moveTo(){}lineTo(){}stroke(){this.ops.push({op:'guide'})}}
 class Element{constructor(tag){this.tagName=tag;this.children=[];this.events={};this.dataset={};this.style={};this.checked=false;this.disabled=false;this.value='';this.className='';this.classes=new Set();this.classList={toggle:(s,v)=>v?this.classes.add(s):this.classes.delete(s)};this.ctx=new Context();all.push(this)}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=nodes}addEventListener(e,f){(this.events[e]??=[]).push(f)}emit(e){this['on'+e]?.({preventDefault(){}});for(const f of this.events[e]??[])f({preventDefault(){}})}click(){if(this.download)downloads.push({name:this.download,url:this.href});this.emit('click')}remove(){}getBoundingClientRect(){return {left:0,top:0,width:600,height:448}}getContext(){return this.ctx}toDataURL(){return 'data:image/mock,'+encodeURIComponent(JSON.stringify({width:this.width,height:this.height,ops:this.ctx.ops}))}}
 for(const m of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=new Element(m[1]);e.id=m[2];e.checked=/\bchecked\b/.test(m[0]);e.value=m[0].match(/value="([^"]*)"/)?.[1]??'';ids[e.id]=e}
 const document={getElementById:id=>ids[id],createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),body:new Element('body'),querySelectorAll:q=>all.filter(e=>q[0]==='.'&&e.className.split(' ').includes(q.slice(1)))};
 const blobs=new Map();let serial=0;
 const URL={createObjectURL:blob=>{const id='blob:mock-'+(++serial);blobs.set(id,blob);return id},revokeObjectURL:id=>blobs.delete(id)};
 class Img{set src(v){this._src=v;queueMicrotask(async()=>{let ok;if(v.startsWith('blob:')){const bytes=Buffer.from(await blobs.get(v).arrayBuffer());ok=bytes.subarray(1,4).toString()==='PNG'}else ok=fs.existsSync(path.resolve(path.dirname(file),v))||fs.existsSync(path.resolve(temp,v));if(ok){this.width=600;this.height=448;this.onload?.()}else this.onerror?.()})}get src(){return this._src}}
 const context=vm.createContext({document,Image:Img,Blob,URL,TextDecoder,fetch:async p=>{const b=fs.readFileSync(path.resolve(path.dirname(file),p));return{ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}},location:{pathname:'/'+path.basename(file)},console,structuredClone,performance:{now:()=>0},requestAnimationFrame:f=>timers.push(f),setTimeout:()=>0,window:{addEventListener(){}},setInterval:f=>(timers.push(f),timers.length)});ids.scene.width=600;ids.scene.height=448;ids.gain.value='1';ids.direction.value='N';ids.frame.value='0';vm.runInContext(script,context);
 const run=s=>vm.runInContext(s,context),settle=()=>new Promise(r=>setImmediate(r));await settle();
 assert(run('ready'));assert.equal(run('DATA.objects.length'),8);assert.equal(ids.cards.children.length,8);assert.equal(run('placements.length'),4);assert.equal(run('paths.length'),29);assert.equal(ids.scene.ctx.ops.filter(o=>o.op==='image').length,4);
 for(let n=1;n<=16;n++){run(`animate(${n*100})`);assert.equal(run('frame'),n%16)}assert.equal(run('frame'),0);
 ids.step.emit('click');assert.equal(run('frame'),1);assert.equal(run('playing'),false);assert.equal(ids.counter.textContent,'02 / 16');ids.frame.value='9';ids.frame.emit('input');assert.equal(run('frame'),9);
 const light=run("layer('light')");assert.equal(light.ctx.ops.length,5);assert.equal(light.ctx.ops.at(-1).composite,'destination-in');assert.equal(light.ctx.ops[0].args[0],9*96);assert.equal(light.ctx.ops[0].args.length,8);assert.equal(light.ctx.ops[0].alpha,1);
 ids.light.checked=false;ids.light.emit('input');assert.equal(ids.scene.ctx.ops.filter(o=>o.op==='image').length,3);ids.light.checked=true;ids.light.emit('input');
 for(const [id,kind] of [['exportSupport','support'],['exportFire','fire'],['exportLight','light']]){ids[id].emit('click');const d=downloads.at(-1);assert(d.name.includes(kind));const state=JSON.parse(decodeURIComponent(d.url.split(',')[1]));assert.equal(state.width,600);assert.equal(state.height,448);assert(!state.ops.some(o=>o.op==='fill'));assert.equal(state.ops.length,kind==='light'?5:4)}
 ids.clear.emit('click');assert.equal(run('placements.length'),0);ids.direction.value='SE';ids.scene.onclick({clientX:201,clientY:121});assert.equal(run('placements.length'),1);assert.equal(run('placements[0].direction'),'SE');assert.equal(run('placements[0].x'),200);assert.equal(run('placements[0].y'),120);ids.undo.emit('click');assert.equal(run('placements.length'),0);ids.reset.emit('click');assert.equal(run('placements.length'),4);
 ids.background.checked=false;ids.magenta.checked=true;ids.magenta.emit('input');assert(ids.scene.ctx.ops.some(o=>o.color==='#ff00ff'));ids.exportSupport.emit('click');assert(!JSON.parse(decodeURIComponent(downloads.at(-1).url.split(',')[1])).ops.some(o=>o.op==='fill'));
 ids.gain.value='.5';ids.gain.emit('input');assert.equal(run("layer('light')").ctx.ops[0].alpha,.5);ids.exportJson.emit('click');assert(downloads.at(-1).name.endsWith('_positions.json'));
 console.log('PASS DOM',path.relative(R,file),'16 animation steps + wrap, layer controls, strip cropping, transparent exports, placement and undo, JSON, alpha clipping');
}
(async()=>{for(const f of [path.join(O,'index.html'),path.join(R,'apercu_spinda_torches.html'),path.join(temp,'index.html')])await check(f);fs.writeFileSync(path.join(O,'verification_viewer.json'),JSON.stringify({pass:true,variants:['repository','redirect','standalone extracted ZIP'],checks:['16 animation steps + wrap','pause and frame slider','8 angle cards','RGBA strip cropping','3 transparent PNG exports','light alpha bound to room','placement grid + undo + reset','position JSON'],method:'Node DOM/canvas mocks, not graphical browser or PMDO'},null,2)+'\n')})().catch(e=>{console.error(e);process.exitCode=1});
