/* DOM/state tests, not a graphical browser or PMDO runtime test. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),cp=require('child_process');
const R=path.resolve(__dirname,'../..'),O=path.join(R,'renders/cafe_spinda_revisite_v8'),temp=path.join(R,'.cache/spinda8/package');
fs.rmSync(temp,{recursive:true,force:true});
cp.execFileSync(path.join(R,'.venv/bin/python'),['-c',`import zipfile;zipfile.ZipFile(${JSON.stringify(path.join(O,'SpindaV8_atelier_lot1.zip'))}).extractall(${JSON.stringify(temp)})`]);
async function check(file){
 const html=fs.readFileSync(file,'utf8');if(html.includes('http-equiv="refresh"')){assert(html.includes('url=renders/cafe_spinda_revisite_v8/index.html'));assert(fs.existsSync(path.join(O,'index.html')));console.log('PASS root redirect');return}const script=html.match(/<script>([\s\S]*?)<\/script>/)[1],all=[],ids={},downloads=[],timers=[];
 class Context{constructor(){this.ops=[]}clearRect(){this.ops=[]}drawImage(im,...args){this.ops.push({op:'image',src:im.src,args})}fillRect(){this.ops.push({op:'fill',color:this.fillStyle})}strokeRect(){this.ops.push({op:'guide'})}fillText(){this.ops.push({op:'guide'})}beginPath(){}moveTo(){}lineTo(){}stroke(){this.ops.push({op:'guide'})}}
 class Element{constructor(tag){this.tagName=tag;this.children=[];this.events={};this.dataset={};this.style={};this.checked=false;this.disabled=false;this.value='';this.className='';this.classes=new Set();this.classList={toggle:(s,v)=>v?this.classes.add(s):this.classes.delete(s)};this.ctx=new Context();all.push(this)}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=nodes}addEventListener(e,f){(this.events[e]??=[]).push(f)}emit(e){this['on'+e]?.({preventDefault(){}});for(const f of this.events[e]??[])f({preventDefault(){}})}click(){if(this.download)downloads.push({name:this.download,url:this.href});this.emit('click')}remove(){}getContext(){return this.ctx}toDataURL(){return 'data:image/mock,'+encodeURIComponent(JSON.stringify({width:this.width,height:this.height,ops:this.ctx.ops}))}}
 for(const m of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=new Element(m[1]);e.id=m[2];e.checked=/\bchecked\b/.test(m[0]);e.value=m[0].match(/value="([^"]*)"/)?.[1]??'';ids[e.id]=e}
 const document={getElementById:id=>ids[id],createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),body:new Element('body'),querySelectorAll:q=>all.filter(e=>q[0]==='.'&&e.className.split(' ').includes(q.slice(1)))};
 const blobs=new Map();let serial=0;
 const URL={createObjectURL:blob=>{const id='blob:mock-'+(++serial);blobs.set(id,blob);return id},revokeObjectURL:id=>blobs.delete(id)};
 class Img{set src(v){this._src=v;queueMicrotask(async()=>{let ok;if(v.startsWith('blob:')){const bytes=Buffer.from(await blobs.get(v).arrayBuffer());ok=bytes.subarray(1,4).toString()==='PNG'}else ok=fs.existsSync(path.resolve(path.dirname(file),v));if(ok){this.width=600;this.height=448;this.onload?.()}else this.onerror?.()})}get src(){return this._src}}
 const context=vm.createContext({document,Image:Img,Blob,URL,TextDecoder,fetch:async p=>{const b=fs.readFileSync(path.resolve(path.dirname(file),p));return{ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}},location:{pathname:'/'+path.basename(file)},console,window:{addEventListener(){}},setInterval:f=>(timers.push(f),timers.length)});ids.scene.width=600;ids.scene.height=448;ids.viewport.clientWidth=850;ids.zoom.value='fit';vm.runInContext(script,context);
 const run=s=>vm.runInContext(s,context),settle=()=>new Promise(r=>setImmediate(r));await settle();
 assert(run('ready'));assert.equal(run('mode'),'nuit');assert.equal(run('current.id'),'cafe');assert.equal(run('DATA.assets.length'),9);
 for(const a of run('DATA.assets')){assert(fs.existsSync(path.resolve(path.dirname(file),a.reference)));for(const f of Object.values(a.files))assert(fs.existsSync(path.resolve(path.dirname(file),f)))}
 for(const mode of ['jour','nuit'])for(const id of ['accueil','casino','salon_bas','cafe','salon_haut']){await run(`select('${id}','${mode}')`);assert(run('ready'));assert.equal(ids.scene.ctx.ops.filter(o=>o.op==='image').length,run('current.modes[mode].layers.length'));assert.equal(ids.ports.children.length,run('Object.values(current.ports).filter(p=>p.target).length'))}
 await run("select('cafe','nuit')");const n=run('images.length'),row=ids.layers.children.at(-1);assert(row.children[1].textContent.includes('diffuse'));row.children[0].checked=false;row.children[0].emit('change');assert.equal(ids.scene.ctx.ops.filter(o=>o.op==='image').length,n-1);row.children[0].checked=true;row.children[0].emit('change');
 ids.grid.checked=true;ids.grid.emit('change');assert(ids.scene.ctx.ops.some(o=>o.op==='guide'));ids.export.emit('click');let d=JSON.parse(decodeURIComponent(downloads.at(-1).url.split(',')[1]));assert.equal(d.width,600);assert.equal(d.ops.filter(o=>o.op==='image').length,n);assert(!d.ops.some(o=>o.op==='guide'||o.op==='fill'));assert(downloads.at(-1).name.includes('cafe_nuit'));
 ids.magenta.checked=true;ids.magenta.emit('change');ids.export.emit('click');d=JSON.parse(decodeURIComponent(downloads.at(-1).url.split(',')[1]));assert(d.ops.some(o=>o.color==='#ff00ff'));ids.layers.children[0].children[2].emit('click');d=JSON.parse(decodeURIComponent(downloads.at(-1).url.split(',')[1]));assert.equal(d.ops.length,1);assert(downloads.at(-1).name.endsWith('_sol.png'));
 await run("Promise.all([select('casino','jour'),select('salon_haut','nuit')])");assert.equal(run('current.id'),'salon_haut');assert.equal(run('mode'),'nuit');assert(await run('Promise.all(current.modes[mode].layers.map(l=>image(l.file))).then(expected=>expected.every((im,i)=>im===images[i]))'));
 ids.ports.children[0].emit('click');await settle();assert.equal(run('current.id'),'cafe');ids.day.emit('click');await settle();assert.equal(run('mode'),'jour');assert(ids.sheet.href.endsWith('_jour.png'));assert(ids.assets.children[0].children[0].children[1].src.endsWith('_jour.png'));
 console.log('PASS DOM',path.relative(R,file),'10 room/mode states, light toggle, asset URLs, guide-free exports, transparency, layer PNG, ZIP decode, async race guard');
}
(async()=>{for(const file of [path.join(O,'index.html'),path.join(R,'apercu_cafe_spinda_revisite_v8.html'),path.join(temp,'index.html')])await check(file);fs.writeFileSync(path.join(O,'verification_viewer.json'),JSON.stringify({pass:true,variants:['repository ZIP-backed','root redirect','extracted PNG ZIP'],checks:['10 room/mode states','light toggle','native/generated reference URLs','guide-free PNG export state','transparent/magenta export','single layer export','navigation race guard'],method:'Node vm with DOM/canvas mocks, not graphical browser or PMDO'},null,2)+'\n')})().catch(e=>{console.error(e);process.exitCode=1});
