// DOM simulation only. No claim of graphical-browser or PMDO validation.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'renders/beach_extension_v2');
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.clientWidth=840;this.value='';this.hidden=false;this.checked=false;this.ops=[];this.downloads=[]}set innerHTML(v){this.children=[]}append(...xs){this.children.push(...xs)}querySelectorAll(tag){return this.children.flatMap(c=>[(c.tag===tag?c:null),...c.querySelectorAll(tag)].filter(Boolean))}getContext(){return{clearRect:()=>{this.ops=[]},fillRect(){},drawImage:(im,...args)=>this.ops.push([im.src,...args]),save(){},restore(){},beginPath(){},rect(){},clip(){},moveTo(){},lineTo(){},stroke(){},fillText(){}}}getBoundingClientRect(){return{left:0,top:0,width:this.width,height:this.height}}toDataURL(){return'data:image/png;base64,TEST'}click(){this.downloads.push(this.download)}}
const settle=()=>new Promise(r=>setImmediate(r));
function create(html,base){const ids={},files=[],downloads=[];for(const m of html.matchAll(/id="([^"]+)"/g))ids[m[1]]=new Element(m[1]==='view'?'canvas':'div');ids.zoom.value='fit';ids.view.width=1024;ids.view.height=1024;const legend=new Element('div');class MockImage{set src(v){this._src=v;files.push(v);queueMicrotask(()=>fs.existsSync(path.join(base,v))?this.onload():this.onerror())}get src(){return this._src}}
const sandbox={console,Math,Number,String,JSON,Promise,Map,Image:MockImage,document:{getElementById:k=>ids[k],querySelector:()=>legend,createElement:tag=>{const e=new Element(tag);e.click=()=>downloads.push(e.download);return e}},window:{addEventListener(){}},requestAnimationFrame(){}};vm.createContext(sandbox);const run=s=>vm.runInContext(s,sandbox);run(html.match(/<script>([\s\S]*?)<\/script>/)[1]);return{ids,run,files,downloads,base,legend}}
(async()=>{
const full=create(fs.readFileSync(path.join(root,'apercu_extension_plage_v2.html'),'utf8'),root);await settle();let{ids,run}=full;
assert.equal(run('ready'),true);assert.equal(run('chosen.length'),4);assert.equal(ids.layers.querySelectorAll('input').length,11);
ids.play.onclick();assert.equal(run('playing'),false);const zero=JSON.stringify(ids.view.ops);ids.wrap.onclick();assert.equal(run('elapsed'),64000);assert.equal(JSON.stringify(ids.view.ops),zero);ids.wrap.onclick();assert.equal(run('elapsed'),0);
ids.scrub.oninput({target:{value:'1600'}});assert.notEqual(JSON.stringify(ids.view.ops),zero);
let ch=ids.layers.querySelectorAll('input')[0];ch.checked=false;ch.onchange();assert.equal(run('enabled["01_sable"]'),false);ids.all.onclick();assert.equal(run('enabled["01_sable"]'),true);
ids.layers.children[0].children[2].onclick({preventDefault(){}});assert.ok(full.downloads.at(-1).includes('01_sable'));ids.export.onclick();assert.ok(full.downloads.at(-1).endsWith('.png'));const originalExport=ids.view.toDataURL;ids.view.toDataURL=()=>{throw new Error('tainted local-file canvas')};ids.export.onclick();run('draw()');assert.ok(ids.status.textContent.includes('HTTP local'));ids.view.toDataURL=originalExport;ids.export.onclick();
ids.view.onclick({clientX:256,clientY:256});await settle();assert.equal(run('selection'),'07_carrefour_dunes');assert.equal(ids.view.width,512);
ids.ports.children[0].onclick();await settle();assert.equal(run('selection'),'05_carrefour_croix');ids.ports.children[2].onclick();await settle();assert.equal(run('selection'),'07_carrefour_dunes');
ids.room.value='09_place_palmes';ids.room.onchange();await settle();ids.ports.children[2].onclick();assert.equal(run('selection'),'09_place_palmes');run('draw()');assert.ok(ids.status.textContent.includes('réservée'));
ids.network.onclick();await settle();assert.equal(run('chosen.length'),10);assert.equal(ids.view.height,2160);assert.equal(ids.layers.querySelectorAll('input').length,13);ids.view.onclick({clientX:128,clientY:1400});assert.equal(run('selection'),'reseau');ids.view.onclick({clientX:1280,clientY:1904});await settle();assert.equal(run('selection'),'10_baie_abritee');
ids.plan.onclick();assert.equal(run('guides'),true);ids.plan.onclick();assert.equal(run('guides'),false);
ids.reference.onclick();await settle();assert.equal(ids.view.width,702);assert.equal(ids.view.height,578);ids.night.onclick();await settle();assert.equal(run('mode'),'nuit');assert.ok(ids.view.ops.some(x=>x[0].includes('ciel_nuit')));
ch=ids.layers.querySelectorAll('input')[1];ch.checked=false;ch.onchange();assert.ok(!ids.view.ops.some(x=>x[0].includes('nuages')));
ids.zoom.value='2';ids.zoom.onchange();assert.equal(ids.view.style.width,'1404px');run('playing=true;elapsed=63900;last=100;tick(250)');assert.equal(run('elapsed'),50);
ids.day.onclick();ids.night.onclick();await settle();assert.equal(run('mode'),'nuit');assert.equal(run('ready'),true);
for(const key of ['pack','still','readme','previous'])assert.ok(fs.existsSync(path.join(root,ids[key].href)),key);
const tmp=fs.mkdtempSync(path.join(root,'.cache/beach-extension-dom-'));try{
 cp.execFileSync('python',['-c','import zipfile,sys;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',path.join(out,'BeachExtension_4modules.zip'),tmp]);
 const portable=create(fs.readFileSync(path.join(tmp,'index.html'),'utf8'),tmp);await settle();assert.equal(portable.run('ready'),true);assert.equal(portable.run('DATA.rooms.length'),4);assert.equal(portable.ids.network.hidden,true);assert.equal(portable.legend.hidden,true);
 portable.ids.view.onclick({clientX:256,clientY:256});await settle();portable.ids.ports.children[0].onclick();assert.equal(portable.run('selection'),'07_carrefour_dunes');assert.ok(portable.ids.status.textContent.includes('externe'));
 portable.ids.night.onclick();await settle();assert.equal(portable.run('ready'),true);assert.ok(portable.files.every(p=>!p.includes('..')&&fs.existsSync(path.join(tmp,p))));
}finally{fs.rmSync(tmp,{recursive:true,force:true})}
assert.ok(full.files.every(p=>fs.existsSync(path.join(root,p))));
const report={pass:true,scope:'Simulated DOM: combined and extracted standalone viewers; scene loading, day/night, animation, wrap, scrub, layers, PNG download actions, zoom, guides, map clicks, empty slots, old/new navigation, reserved and external ports, load races, persistent notices, file-origin export error handling, local resources and links.',browser:'NOT TESTED: no graphical browser installed',runtime_PMDO:'NOT TESTED'};fs.writeFileSync(path.join(out,'verification_viewer.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS combined + portable viewer interactions (simulated DOM only).');
})().catch(e=>{console.error(e);process.exitCode=1});
