from pathlib import Path
import json,base64
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'exports/guild_eat_all_v6'
DESCS={'0282':'Geste raffiné, bras fin près du visage ; cycle V5 conservé.','0083':'Petite inclinaison de la tête et mouvement du bec ; poireau préservé dans son aile.','0674':'Pattes courtes rapprochées du museau ; feuille et proportions natives conservées.','0371':'Vraie animation Eat native, dessins et timings inchangés.','0285':'Inclinaison du corps au-dessus des pieds fixes, sans bras inventés ; V5 conservée.','0440':'Vraie animation Eat native, dessins et timings inchangés.','0417':'Vraie animation Eat native, dessins et timings inchangés.','0461':'Griffes natives rapprochées sous le museau, sans nouveaux doigts ni changement de crête.','0186':'Pattes antérieures ramenées vers la mâchoire, petite déglutition ; antenne conservée.'}
def uri(p):return 'data:image/gif;base64,'+base64.b64encode(p.read_bytes()).decode()
def main():
 r=json.loads((OUT/'verification.json').read_text())
 html='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Eat · Les neuf membres de la guilde</title><style>body{font:16px system-ui;max-width:1200px;margin:32px auto;padding:0 24px;background:#141d2b;color:#edf4fa}p,li{line-height:1.6;color:#bed0df}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:20px}section{background:#232f3c;padding:22px;border-radius:14px}img{image-rendering:pixelated;max-width:100%}.badge{color:#b4e4be;font-size:14px}.note{border-left:3px solid #f4c477;padding:14px}summary{cursor:pointer;color:#cbddec}details{margin-top:15px}</style><h1>Eat pour les neuf membres de la guilde</h1><p>9/9 ont une ressource Eat dans ce lot : quatre créations candidates, deux cycles V5 conservés et trois animations canoniques natives. Aucune nourriture n’est ajoutée dans les sprites : repas et émote sont des éléments de scène distincts.</p><p class="note">Les six cycles créés ont huit vues. Draby, Ptiravi et Pachirisu gardent leur unique vue Eat canonique : pas de fausses directions miroitées. Formats contrôlés localement ; les quatre nouveaux gestes restent à examiner artistiquement et aucun test PMDO n’est revendiqué.</p><div class="grid">'''
 for m in r['members']:
  slot=m['slot'];label={'native_preserved':'Natif conservé · 1 vue canonique','v5_cycle_retained':'V5 conservée · 8 vues','new_technical_candidate':'Nouveau candidat · 8 vues'}[m['state']]
  html+='<section><h2>'+m['name']+'</h2><p class="badge">'+label+'</p><img alt="Eat '+m['name']+'" src="'+uri(OUT/'review'/f'{slot}_Eat_D.gif')+'"><p>'+DESCS[slot]+'</p>'
  if m['directions']==8:
   html+='<details><summary>Voir les huit directions</summary><img alt="Eat huit directions '+m['name']+'" src="'+uri(OUT/'review'/f'{slot}_Eat_8directions.gif')+'"></details>'
  html+='</section>'
 html+='</div><h2>Fichiers et statut</h2><p>exports/guild_eat_all_v6/ : neuf packs XML/triples complets, crédits séparés,57GIFs, planches de contrôle et rapport technique. Les originaux et les cartes ajoutées par l’utilisateur restent intacts. Les dessins générés ont été utilisés comme études de gestuelle ; leurs erreurs anatomiques ne sont pas acceptées comme des exports natifs.</p><p>Toutes les propositions de guilde précédemment présentées sont retenues dans le programme. Cela ne signifie pas que les autres scènes, bâtiments ou animations encore à produire sont terminés.</p></html>'
 (ROOT/'apercu_guilde_eat_tous_v6.html').write_text(html)
if __name__=='__main__':main()
