// Simulated DOM interactions, NOT a graphical browser test.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),cp=require('node:child_process');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'renders/casino_network_v1');
function create(html,base){const ids={},downloads=[],requests=[];
class Element{constructor(tag){this.tag=tag;this.children=[];this.style={};this.checked=false;this.value='';this.hidden=false;this.clientWidth=824;this.ops=[]}set id(v){this._id=v;ids[v]=this}get id(){return this._id}append(...x){this.children.push(...x)}querySelectorAll(tag){return this.children.flatMap(c=>[(c.tag===tag?c:null),...c.querySelectorAll(tag)].filter(Boolean))}getContext(){return{clearRect:()=>{this.ops=[]},drawImage:(im,...args)=>this.ops.push([im.src,...args]),strokeRect(){},fillRect(){},fillText(){}}}getBoundingClientRect(){return{left:0,top:0,width:this.width,height:this.height}}toDataURL(){return'data:image/png;base64,TEST'}click(){downloads.push({file:this.download,href:this.href})}}
for(const m of html.matchAll(/<[^>]*\bid="([^"]+)"[^>]*>/g)){const el=new Element(m[1]==='view'?'canvas':'div');el.id=m[1];el.hidden=/\bhidden\b/.test(m[0])}ids.view.width=1024;ids.view.height=1024;ids.zoom.value='fit';
class MockImage{set src(v){this._src=v;requests.push(v);queueMicrotask(()=>fs.existsSync(path.join(base,v))?this.onload():this.onerror())}get src(){return this._src}}
const sandbox={console,Math,Number,String,JSON,Promise,Set,Object,Image:MockImage,Blob:class{constructor(data){this.data=data}},URL:{createObjectURL(){return'blob:test'},revokeObjectURL(){}},setTimeout:f=>f(),document:{getElementById:id=>ids[id],createElement:tag=>new Element(tag),createTextNode:text=>new Element('#text')},window:{addEventListener(){}},requestAnimationFrame(){}};
vm.createContext(sandbox);const run=s=>vm.runInContext(s,sandbox);run(html.match(/<script>([\s\S]*?)<\/script>/)[1]);return{ids,run,downloads,requests,base}}
const settle=()=>new Promise(r=>setImmediate(r));
(async()=>{
const full=create(fs.readFileSync(path.join(root,'apercu_casino_reseau_v1.html'),'utf8'),root);await settle();const{ids,run}=full;
assert.equal(run('ready'),true);assert.equal(ids.layers.querySelectorAll('input').length,38);assert.equal(ids.view.ops.length,38);
ids.play.onclick();assert.equal(run('playing'),false);const zero=JSON.stringify(ids.view.ops);ids.next.onclick();assert.equal(run('frame'),1);assert.notEqual(JSON.stringify(ids.view.ops),zero);ids.scrub.value='3';ids.scrub.oninput();ids.next.onclick();assert.equal(run('frame'),0);assert.equal(JSON.stringify(ids.view.ops),zero);
ids.bare.onclick();assert.equal(ids.view.ops.length,5);ids.furnished.onclick();assert.equal(ids.view.ops.length,38);
ids.group_flammes.checked=false;ids.group_flammes.onchange();assert.equal(ids.view.ops.length,28);ids.group_flammes.checked=true;ids.group_flammes.onchange();
ids.check_fourneau_salon.checked=false;ids.check_fourneau_salon.onchange();assert.equal(ids.view.ops.length,36);assert.ok(!ids.view.ops.some(op=>op[0].includes('flamme_native')&&op[1]===904&&op[2]===144));ids.furnished.onclick();
ids.object.value='fourneau_salon';ids.object.onchange();const x=Number(ids.px.value);ids.px.value=x+16;ids.apply.onclick();assert.equal(run('DATA.layers.find(l=>l.id==="fourneau_salon").position[0]'),x+16);assert.equal(run('DATA.layers.find(l=>l.id==="feu_fourneau_salon").position[0]'),x+48);ids.positions.onclick();assert.equal(full.downloads.at(-1).file,'Casino_positions.json');ids.reset.onclick();assert.equal(run('DATA.layers.find(l=>l.id==="fourneau_salon").position[0]'),x);
ids.view.onclick({clientX:256,clientY:768});assert.equal(run('selection'),'accueil');assert.equal(ids.view.width,512);ids.zoom.value='2';ids.zoom.onchange();assert.equal(ids.view.style.width,'1024px');
ids.paths.onclick();assert.equal(run('guides'),true);ids.export.onclick();assert.ok(full.downloads.at(-1).file.includes('accueil'));ids.layers.children[0].children[2].onclick({preventDefault(){}});assert.ok(full.downloads.at(-1).file.includes('sol'));
const original=ids.view.toDataURL;ids.view.toDataURL=()=>{throw Error('local origin')};ids.export.onclick();assert.ok(ids.status.textContent.includes('HTTP'));ids.view.toDataURL=original;
run('playing=true;elapsed=350;frame=3;last=100;tick(200)');assert.equal(run('frame'),0);
for(const k of ['pack','still','animation','docs','native'])assert.ok(fs.existsSync(path.join(root,ids[k].href)),k);
assert.ok(full.requests.every(p=>fs.existsSync(path.join(root,p))));
const tmp=fs.mkdtempSync(path.join(root,'.cache/casino-dom-'));try{cp.execFileSync('python',['-c','import sys,zipfile;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',path.join(out,'Casino_pack.zip'),tmp]);const portable=create(fs.readFileSync(path.join(tmp,'index.html'),'utf8'),tmp);await settle();assert.equal(portable.run('ready'),true);assert.equal(portable.ids.pack.hidden,true);assert.equal(portable.ids.still.hidden,true);assert.equal(portable.ids.animation.hidden,true);assert.ok(portable.requests.every(p=>fs.existsSync(path.join(tmp,p))));portable.ids.next.onclick();assert.equal(portable.run('frame'),1)}finally{fs.rmSync(tmp,{recursive:true,force:true})}
const report={pass:true,scope:'Combined/extracted portable viewer DOM: load, play/pause, 4-pose wrap, native-size draw calls, terrain-only/furnished, groups/individual objects, host/flame dependency, placement with attached fire, reset, position export, PNG downloads, sector crop, zoom, guides, file-origin errors, links.',browser:'NOT TESTED: no graphical browser installed',runtime_PMDO:'NOT TESTED'};fs.writeFileSync(path.join(out,'verification_viewer.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS casino viewer (DOM simulation, including extracted portable pack).')
})().catch(e=>{console.error(e);process.exitCode=1});
