/* DOM/state tests, not a graphical browser or PMDO runtime test. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),cp=require('child_process');
const R=path.resolve(__dirname,'../..'),O=path.join(R,'renders/cafe_spinda_revisite_v7'),temp=path.join(R,'.cache/spinda7/package');
fs.rmSync(temp,{recursive:true,force:true});
cp.execFileSync(path.join(R,'.venv/bin/python'),['-c',`import zipfile;zipfile.ZipFile(${JSON.stringify(path.join(O,'SpindaV7_complet.zip'))}).extractall(${JSON.stringify(temp)})`]);
async function check(file){
 const html=fs.readFileSync(file,'utf8');if(html.includes('http-equiv="refresh"')){assert(html.includes('url=renders/cafe_spinda_revisite_v7/index.html'));assert(fs.existsSync(path.join(O,'index.html')));console.log('PASS root redirect');return}const script=html.match(/<script>([\s\S]*?)<\/script>/)[1],all=[],ids={},downloads=[],timers=[];
 class Context{constructor(){this.ops=[]}clearRect(){this.ops=[]}drawImage(im,...args){this.ops.push({op:'image',src:im.src,args})}fillRect(){this.ops.push({op:'fill',color:this.fillStyle})}strokeRect(){this.ops.push({op:'guide'})}fillText(){this.ops.push({op:'guide'})}beginPath(){}moveTo(){}lineTo(){}stroke(){this.ops.push({op:'guide'})}}
 class Element{constructor(tag){this.tagName=tag;this.children=[];this.events={};this.dataset={};this.style={};this.checked=false;this.disabled=false;this.value='';this.className='';this.classes=new Set();this.classList={toggle:(s,v)=>v?this.classes.add(s):this.classes.delete(s)};this.ctx=new Context();all.push(this)}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=nodes}addEventListener(e,f){(this.events[e]??=[]).push(f)}emit(e){for(const f of this.events[e]??[])f({preventDefault(){}})}click(){if(this.download)downloads.push({name:this.download,url:this.href});this.emit('click')}remove(){}getContext(){return this.ctx}toDataURL(){return 'data:image/mock,'+encodeURIComponent(JSON.stringify({width:this.width,height:this.height,ops:this.ctx.ops}))}}
 for(const m of html.matchAll(/<([a-z]+)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=new Element(m[1]);e.id=m[2];e.checked=/\bchecked\b/.test(m[0]);e.value=m[0].match(/value="([^"]*)"/)?.[1]??'';ids[e.id]=e}
 const document={getElementById:id=>ids[id],createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),body:new Element('body'),querySelectorAll:q=>all.filter(e=>q[0]==='.'&&e.className.split(' ').includes(q.slice(1)))};
 const blobs=new Map();let serial=0;
 const URL={createObjectURL:blob=>{const id='blob:mock-'+(++serial);blobs.set(id,blob);return id},revokeObjectURL:id=>blobs.delete(id)};
 class Img{set src(v){this._src=v;queueMicrotask(async()=>{let ok;if(v.startsWith('blob:')){const bytes=Buffer.from(await blobs.get(v).arrayBuffer());ok=bytes.subarray(1,4).toString()==='PNG'}else ok=fs.existsSync(path.resolve(path.dirname(file),v));if(ok){this.width=600;this.height=448;this.onload?.()}else this.onerror?.()})}get src(){return this._src}}
 const context=vm.createContext({document,Image:Img,Blob,URL,TextDecoder,fetch:async p=>{const b=fs.readFileSync(path.resolve(path.dirname(file),p));return{ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}},location:{pathname:'/'+path.basename(file)},console,setInterval:f=>(timers.push(f),timers.length)});vm.runInContext(script,context);
 const run=s=>vm.runInContext(s,context),settle=()=>new Promise(r=>setImmediate(r));await settle();
 assert.equal(run('ready'),true);assert.equal(ids.title.textContent,'Accueil de Spinda');assert.equal(ids.scene.width,600);assert.equal(ids.scene.height,448);assert.equal(ids.scene.ctx.ops.filter(o=>o.op==='image').length,6);
 assert.equal(run('DATA.assets.length'),39);for(const a of run('DATA.assets'))assert(fs.existsSync(path.resolve(path.dirname(file),a.file)));
 for(const id of ['casino','salon_bas','cafe','salon_haut','accueil']){await run(`selectRoom('${id}')`);assert.equal(run('current.id'),id);assert(run('ready'));assert.equal(ids.scene.ctx.ops.filter(o=>o.op==='image').length,run('current.layers.filter(l=>l.default).length'));assert.equal(ids.connections.children.length,run('Object.values(current.ports).filter(p=>p.target).length'));}
 await run("selectRoom('cafe')");
 const windowBox=ids.layers.children.find(row=>row.children[1].textContent.includes('oculus')).children[0];windowBox.checked=false;windowBox.emit('change');assert.equal(ids.scene.ctx.ops.filter(o=>o.op==='image').length,5);windowBox.checked=true;windowBox.emit('change');
 ids.grid.checked=true;ids.grid.emit('change');ids.guides.checked=true;ids.guides.emit('change');assert(ids.scene.ctx.ops.some(o=>o.op==='guide'));
 ids.export.emit('click');let last=downloads.at(-1),data=JSON.parse(decodeURIComponent(last.url.split(',')[1]));assert(last.name.includes('cafe'));assert.equal(data.width,600);assert(!data.ops.some(o=>o.op==='guide'));assert.equal(data.ops.filter(o=>o.op==='image').length,6);assert(data.ops.some(o=>o.color==='#ff00ff'));
 ids.magenta.checked=false;ids.magenta.emit('change');ids.export.emit('click');data=JSON.parse(decodeURIComponent(downloads.at(-1).url.split(',')[1]));assert(!data.ops.some(o=>o.op==='fill'));
 ids.layers.children[0].children[2].emit('click');assert(downloads.at(-1).name.endsWith('_sol.png'));data=JSON.parse(decodeURIComponent(downloads.at(-1).url.split(',')[1]));assert.equal(data.ops.filter(o=>o.op==='image').length,1);assert(!data.ops.some(o=>o.op==='guide'));
 await run("Promise.all([selectRoom('casino'),selectRoom('salon_haut')])");assert.equal(run('current.id'),'salon_haut');assert.equal(ids.title.textContent,'Salon des croisillons');assert(await run('Promise.all(current.layers.map(l=>image(l.file))).then(expected=>expected.every((im,i)=>im===images[i]))'));
 const frames=[];for(let i=0;i<4;i++){timers[0]();frames.push(ids.fire.src)}assert.equal(new Set(frames).size,4);assert(frames.at(-1).endsWith('_00.png'));
 ids.connections.children[0].emit('click');await settle();assert.equal(run('current.id'),'cafe');assert(!ids.status.textContent.includes('impossible'));
 console.log('PASS DOM',path.relative(R,file),'navigation, layers, integrated access layers, PNG export state, guides excluded, native animation, ZIP-backed PNG decoder, race protection');
}
(async()=>{for(const file of [path.join(O,'index.html'),path.join(R,'apercu_cafe_spinda_revisite_v7.html'),path.join(temp,'index.html')])await check(file);fs.writeFileSync(path.join(O,'verification_viewer.json'),JSON.stringify({pass:true,variants:['repository','root redirect target','extracted PNG ZIP'],checks:['5-room navigation','layer and café-window toggles','PNG export state without guides','magenta/transparency export state','all asset URLs resolve','4-pose catalog animation','asynchronous navigation race guard'],method:'Node vm with DOM/canvas mocks; no graphical rasterization or PMDO test'},null,2)+'\n')})().catch(e=>{console.error(e);process.exit(1)});
