from pathlib import Path
import json,base64,io
from PIL import Image
ROOT=Path(__file__).resolve().parents[2]
BASE='https://github.com/meromoonmeri/guilde-treehouse-pmd/blob/arena/01a095e8-guilde-treehouse-pmd/'
def preview(path):
 im=Image.open(ROOT/path).convert('RGBA');im.thumbnail((480,400),Image.Resampling.NEAREST);b=io.BytesIO();im.save(b,format='WEBP',lossless=True);return 'data:image/webp;base64,'+base64.b64encode(b.getvalue()).decode()
rows=json.loads((ROOT/'renders/retouches_zones_v6/manifest.json').read_text());zones=[]
for r in rows:
 slug=r['id'];z={'id':slug,'status':r['status'],'size':r['size']}
 for phase in ['jour','nuit']:
  before=f'renders/metano_expeditions_actuel/{slug}/{phase}.png';after=f'renders/retouches_zones_v6/{slug}'+('_nuit' if phase=='nuit' else '')+'.png'
  z[phase]={'before':preview(before),'after':preview(after),'link':BASE+after}
 zones.append(z)
kits=[]
for r in json.loads((ROOT/'renders/entrees_calques_v6/manifest.json').read_text()):
 k={'id':r['id'],'size':r['canvas'],'ora':BASE+f'renders/entrees_calques_v6/{r["id"]}/{r["id"]}.ora'}
 for phase in ['jour','nuit']:
  k[phase]=[{'name':n,'image':preview(f'renders/entrees_calques_v6/{r["id"]}/{n}'+('_nuit' if phase=='nuit' else '')+'.png'),'link':BASE+f'renders/entrees_calques_v6/{r["id"]}/{n}'+('_nuit' if phase=='nuit' else '')+'.png'} for n in r['layers']]
 kits.append(k)
page='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Retouches et calques · PMD V6</title><style>
*{box-sizing:border-box}body{margin:0;background:#10212d;color:#e6eee7;font:16px/1.55 system-ui}header,main{padding:24px 4%}header{border-bottom:1px solid #39525e}h1{font-size:30px;margin:5px 0}h2{font-size:21px}p{max-width:1050px}a{color:#b7da96}button,select{background:#233e4d;color:#edf0e5;border:1px solid #5d7a83;border-radius:6px;padding:10px;font:inherit;cursor:pointer}button.active{background:#547548}nav{display:flex;gap:10px;flex-wrap:wrap}.controls{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin:18px 0}.notice{padding:13px 18px;border-left:3px solid #d5ab63;background:#263537;color:#edd5ae}.compare{display:grid;grid-template-columns:1fr 1fr;gap:16px}.compare img{width:100%;height:440px;object-fit:contain;background:#0b1820;image-rendering:pixelated}.workspace{display:grid;grid-template-columns:minmax(0,3fr) minmax(240px,1fr);gap:24px}.stack{position:relative;background:repeating-conic-gradient(#233743 0% 25%,#344752 0% 50%) 0/24px 24px;max-height:680px}.stack img{position:absolute;top:0;left:0;width:100%;height:100%;object-fit:fill;image-rendering:pixelated}.layer{padding:16px 10px;border-bottom:1px solid #39525e}.layer a{font-size:13px;display:block;margin-left:24px}small{color:#bdcbc8}section[hidden]{display:none}@media(max-width:750px){.compare,.workspace{grid-template-columns:1fr}.compare img{height:300px}}
</style><header><small>PMD · ATELIER V6 · ORIGINAUX PRÉSERVÉS</small><h1>Retouches des zones & entrées en calques</h1><p>Dix passages au générateur à partir des zones natives existantes. Deux prototypes de calques, extraits des propositions forêt et grotte déjà générées. Rien ne remplace les cartes du mod livré.</p><nav><button id="tab-zones">10 zones · avant / après</button><button id="tab-layers" class="active">Forêt / grotte · calques</button></nav></header><main>
<section id="zones" hidden><div class="controls"><select id="zone" aria-label="Zone"></select><label><input type="checkbox" id="zone-night"> Nuit Abyss</label></div><p class="notice" id="zone-status"></p><div class="compare"><div><h2>Avant · assemblage natif conservé</h2><img id="before" alt="Zone native avant retouche"></div><div><h2>Après · proposition du générateur</h2><img id="after" alt="Proposition générée après retouche"></div></div><p><a id="zone-download">PNG retouché, résolution complète sur GitHub</a></p><small>Les grandes compositions servent de guide, mais les contours et les pixels ne sont pas garantis identiques. Ne pas réutiliser automatiquement les collisions natives.</small></section>
<section id="layers"><div class="controls"><select id="kit" aria-label="Entrée"></select><label><input type="checkbox" id="kit-night"> Nuit Abyss</label><button id="all">Tout afficher</button><button id="no-path">Sans chemin</button></div><p class="notice">Prototypes découpés dans des images existantes, pas de nouvelles générations en calques. Sol caché complété par répétition d’un échantillon : les zones découvertes et certains détourages restent à améliorer. Plans alignés pour cette scène, pas des objets indépendants déplaçables.</p><div class="workspace"><div class="stack" id="stack"></div><aside><h2>Ordre des calques</h2><div id="layer-list"></div><p><a id="ora">Projet OpenRaster (.ora)</a></p><small id="size"></small></aside></div><p>Masquer un calque pour contrôler la séparation. PNG transparents, quatre plans par ambiance. Recomposition complète vérifiée identique aux pixels de l’image source ; aucun test moteur revendiqué.</p></section>
<footer><p><small>Aperçus réduits pour consultation ; les PNG originaux ne sont pas redimensionnés. La limite de dix générations a empêché les reprises des zones 01/04/10 et la génération des nouvelles planches forêt/grotte. Ces étapes restent à faire.</small></p></footer></main>
<script>const ZONES=__ZONES__,KITS=__KITS__;const $=id=>document.getElementById(id);let visible=[true,true,true,true];
function tab(which){for(const id of ['zones','layers']){$(id).hidden=id!==which;$('tab-'+id).classList.toggle('active',id===which)}}
$('tab-zones').onclick=()=>tab('zones');$('tab-layers').onclick=()=>tab('layers');
for(const [i,z] of ZONES.entries())$('zone').add(new Option(z.id.replaceAll('_',' '),i));
for(const [i,k] of KITS.entries())$('kit').add(new Option(k.id.replaceAll('_',' '),i));
function zone(){const z=ZONES[+$('zone').value],v=z[$('zone-night').checked?'nuit':'jour'];$('before').src=v.before;$('after').src=v.after;$('zone-download').href=v.link;$('zone-status').textContent=z.status==='A_REPRENDRE'?'À reprendre : simplification excessive du matériau ou du relief. Cette sortie est conservée pour comparaison, pas validée.':'Proposition à valider : répétitions et raccords retravaillés, mais pas une reconstruction native certifiée.'}
function layers(){const k=KITS[+$('kit').value],rows=k[$('kit-night').checked?'nuit':'jour'];$('stack').innerHTML='';$('layer-list').innerHTML='';const probe=new Image();probe.onload=()=>{$('stack').style.aspectRatio=probe.width+'/'+probe.height};probe.src=rows[0].image;
rows.forEach((r,i)=>{const im=document.createElement('img');im.src=r.image;im.alt=r.name;im.style.display=visible[i]?'block':'none';$('stack').append(im);const box=document.createElement('div');box.className='layer';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=visible[i];check.onchange=()=>{visible[i]=check.checked;im.style.display=check.checked?'block':'none'};label.append(check,document.createTextNode(' '+r.name.replaceAll('_',' ')));const a=document.createElement('a');a.href=r.link;a.textContent='PNG transparent sur GitHub';box.append(label,a);$('layer-list').append(box)});$('ora').href=k.ora;$('size').textContent=k.size.join(' × ')+' px · PNG RGBA · canevas divisible par 8 · non intégré à PMDO'}
$('zone').onchange=zone;$('zone-night').onchange=zone;$('kit').onchange=layers;$('kit-night').onchange=layers;$('all').onclick=()=>{visible=[true,true,true,true];layers()};$('no-path').onclick=()=>{visible=[true,false,true,true];layers()};zone();layers();</script></html>'''
page=page.replace('__ZONES__',json.dumps(zones,ensure_ascii=False)).replace('__KITS__',json.dumps(kits,ensure_ascii=False))
(ROOT/'apercu_retouches_et_calques_v6.html').write_text(page)
print('Self-contained gallery:',round(len(page)/1024/1024,2),'MiB')
